name: Build custom debug kernel
on:
  workflow_dispatch:

jobs:
  build-debug-kernel-a12:
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android12-5.10
      version_name: android12-5.10.198
      tag: android12-5.10-2024-01
      os_patch_level: 2024-01
      patch_path: "5.10"
      debug: true
  build-debug-kernel-wsa:
    strategy:
      matrix:
        arch: [x86_64, arm64]
        version: ["5.15.104.4",]
    uses: ./.github/workflows/wsa-kernel.yml
    with:
      arch: ${{ matrix.arch }}
      version: ${{ matrix.version }}
      debug: true
  build-debug-lkm:
    strategy:
      matrix:
        include:
          - version: "android12-5.10"
            sub_level: 198
            os_patch_level: "2024-01"
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: true
      debug: true
